import { AccessTokens } from './api/accessTokens/AccessTokens.js';
import { Alpha } from './api/alpha/Alpha.js';
import { Apps } from './api/apps/Apps.js';
import { AssetJobs } from './api/assetJobs/AssetJobs.js';
import { Assets } from './api/assets/Assets.js';
import { AssetsV2 } from './api/assetsV2/AssetsV2.js';
import { Cas } from './api/cas/Cas.js';
import { Catalog } from './api/catalog/Catalog.js';
import { Datatables } from './api/datatables/Datatables.js';
import { FastCompositor } from './api/fastCompositor/FastCompositor.js';
import { Files } from './api/files/Files.js';
import { Images } from './api/images/Images.js';
import { Jobs } from './api/jobs/Jobs.js';
import { Layers } from './api/layers/Layers.js';
import { Orders } from './api/orders/Orders.js';
import { Orgs } from './api/orgs/Orgs.js';
import { Pdf } from './api/pdf/Pdf.js';
import { Products } from './api/products/Products.js';
import { SavedConfigurations } from './api/savedConfigurations/SavedConfigurations.js';
import { Tags } from './api/tags/Tags.js';
import { Translations } from './api/translations/Translations.js';
import { Users } from './api/users/Users.js';
import { Variants } from './api/variants/Variants.js';
import { Webhooks } from './api/webhooks/Webhooks.js';
import type { ThreekitAuthProps } from './ThreekitAuthProps.js';

export class ThreekitClient {
  public accesstokens: AccessTokens;
  public alpha: Alpha;
  public apps: Apps;
  public assets: Assets;
  public assetsV2: AssetsV2;
  public assetJobs: AssetJobs;
  public cas: Cas;
  public catalog: Catalog;
  public datatables: Datatables;
  public fastCompositor: FastCompositor;
  public files: Files;
  public images: Images;
  public jobs: Jobs;
  public layers: Layers;
  public orders: Orders;
  public orgs: Orgs;
  public pdf: Pdf;
  public products: Products;
  public savedConfigurations: SavedConfigurations;
  public tags: Tags;
  public translations: Translations;
  public users: Users;
  public variants: Variants;
  public webhooks: Webhooks;

  constructor(public auth: ThreekitAuthProps) {
    this.accesstokens = new AccessTokens(auth);
    this.alpha = new Alpha(auth);
    this.apps = new Apps(auth);
    this.assets = new Assets(auth);
    this.assetsV2 = new AssetsV2(auth);
    this.assetJobs = new AssetJobs(auth);
    this.cas = new Cas(auth);
    this.catalog = new Catalog(auth);
    this.datatables = new Datatables(auth);
    this.fastCompositor = new FastCompositor(auth);
    this.files = new Files(auth);
    this.images = new Images(auth);
    this.jobs = new Jobs(auth);
    this.layers = new Layers(auth);
    this.orders = new Orders(auth);
    this.orgs = new Orgs(auth);
    this.pdf = new Pdf(auth);
    this.products = new Products(auth);
    this.savedConfigurations = new SavedConfigurations(auth);
    this.tags = new Tags(auth);
    this.translations = new Translations(auth);
    this.users = new Users(auth);
    this.variants = new Variants(auth);
    this.webhooks = new Webhooks(auth);
  }
}
